### ISSUE TITLE
Error: conan profile detect --force

### ISSUE THREAD

**Issue by bactone** [conan-io/examples2#112]
when i run `conan profile detect --force`, it reports errors as following:

Found gcc 11.2
gcc>=5, using the major as version
Traceback (most recent call last):
  File "C:\Program Files\Python\Python310\lib\site-packages\conan\cli\cli.py", line 272, in main
    cli.run(args)
  File "C:\Program Files\Python\Python310\lib\site-packages\conan\cli\commands\profile.py", line 65, in profile_detect
    detected_profile = conan_api.profiles.detect()
  File "C:\Program Files\Python\Python310\lib\site-packages\conan\api\subapi\profiles.py", line 97, in detect
    settings = detect_defaults_settings()
  File "C:\Program Files\Python\Python310\lib\site-packages\conans\client\conf\detect.py", line 393, in detect_defaults_settings
    _detect_compiler_version(result)
  File "C:\Program Files\Python\Python310\lib\site-packages\conans\client\conf\detect.py", line 221, in _detect_compiler_version
    libcxx = _detect_gcc_libcxx(version, "g++")
  File "C:\Program Files\Python\Python310\lib\site-packages\conans\client\conf\detect.py", line 188, in _detect_gcc_libcxx
    error, out_str = detect_runner("%s main.cpp -std=c++11" % executable)
  File "C:\Program Files\Python\Python310\lib\site-packages\conans\util\runners.py", line 72, in detect_runner
    line = proc.stdout.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xfc in position 71: illegal multibyte sequence

ERROR: 'gbk' codec can't decode byte 0xfc in position 71: illegal multibyte sequence

how to solve this problem?

**Comment by memsharded** [comment]
Hi @bactone 

I guess this happens irrespective of the ``examples`` repository, if you type in your terminal that command it fails in the same way? (if yes, we will move it to ``conan`` repo).

Can you please confirm:
- Your Conan version
- Your OS (Windows), but any special version?
- Your locale encoding, the language of your OS

As a temporary workaround you can write your default profile manually in your ``<userhome>/.conan2/profiles/default`` file
