### ISSUE TITLE
Where is `examples\libraries\imgui\introduction\run_example.py` should be run from?

### ISSUE THREAD

**Issue by FreePhoenix888** [conan-io/examples2#130]
Where is `examples\libraries\imgui\introduction\run_example.py` should be run from?

# My Tries:
```
PS C:\Users\FreePhoenix\Documents\Programming\examples2\examples\libraries\imgui\introduction> python .\run_example.py
Traceback (most recent call last):
  File "C:\Users\FreePhoenix\Documents\Programming\examples2\examples\libraries\imgui\introduction\run_example.py", line 3, in <module>
    from test.examples_tools import run
ModuleNotFoundError: No module named 'test.examples_tools'
```
```
PS C:\Users\FreePhoenix\Documents\Programming\examples2> python .\examples\libraries\imgui\introduction\run_example.py
Traceback (most recent call last):
  File "C:\Users\FreePhoenix\Documents\Programming\examples2\examples\libraries\imgui\introduction\run_example.py", line 3, in <module>
    from test.examples_tools import run
ModuleNotFoundError: No module named 'test.examples_tools'
```

**Comment by czoido** [comment]
Closing the issue as the question is answered, please feel free to reopen or ask any further questions. Thanks!
