### ISSUE TITLE
Example 'extend_own_cmake_presets' gets Invalid preset: "default"

### ISSUE THREAD

**Issue by ibis-hdl** [conan-io/examples2#166]
I try to follow [CMakeToolchain: Extending your CMakePresets with Conan generated ones](https://docs.conan.io/2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets.html#cmaketoolchain-extending-your-cmakepresets-with-conan-generated-ones)
followed the instructions, or even the `ci_test_example.py`:
```
$ git clone https://github.com/conan-io/examples2.git
$ cd examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets
$ conan install .
...
$ conan install . -s build_type=Debug
$ cmake --list-presets
CMake Error: Could not read presets from /workspaces/conan_extend_own_cmake_presets:
Invalid preset: "default"
$ cmake --preset release
CMake Error: Could not read presets from /workspaces/conan_extend_own_cmake_presets:
Invalid preset: "default"
...
```

I'm using Ubuntu-24.04 with `Conan version 2.9.2` and `cmake version 3.30.5`.

Generally, I've problems with conan2 in real project. My locally generated CMakeUserPreset has schema v3 (why this?), even with same Conan version. Hence, I get:

```
CMake Error: Could not read presets from /workspaces/conan2-test:
File version must be 4 or higher for include support
```

If I changed the version to `"version": 4` my presets are listed as expected.

**Comment by memsharded** [comment]
Hi @ibis-hdl 

Thanks very much for reporting. I have been able to reproduce, I am also getting a ``Invalid preset`` error, not sure from where it is coming or why the CI didn't catch it, we'll iinvestigate it

**Comment by memsharded** [comment]
I was wrong, I could reproduce only because I didn't install both configurations Debug and Release. If only one is installed, the presets will fail, because the way the are defined it requires both configurations to be installed.

But once the 2 configurations are installed
```
cmake --list-presets
Available configure presets:

  "default"       - multi config
  "release"       - release single config
  "debug"         - debug single config
  "conan-default"
  "conan-release" - 'conan-release' config
  "conan-debug"   - 'conan-debug' config
```
I have tested both in Windows and Linux (Ubuntu, CMake 3.30.5 installed)

The inner ``"version": 3,`` only affects the inner ``CMakePresets.json``, but that one is not including other files. And the outer ``ConanPreset.json``, the one that is including the inner ``CMakePresets.json`` does define ``"version": 4,`` so it seems to work.

And the root ``CMakePresets.json`` also has ``"version": 4,``, that looks correct, maybe that was changed somehow?
Do you have ``"version": 3`` in some of the outer presets files?

If you could please try making sure to pull the latest changes form the repo, to ``git clean -xdf`` to guarantee things are clean, then run the ``python ci_test_example.py`` (you might need to ``export PYTHONPATH=<path/to/examples2_repo>:$PYTHONPATH`` first), and past the full output.

**Comment by ibis-hdl** [comment]
Thank you! But, here things are strange. Here what I face

```
vscode ➜ /workspaces/conan_extend_own_cmake_presets (master) $ rm -rf build/
vscode ➜ /workspaces/conan_extend_own_cmake_presets (master) $ conan install .

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.py (foo/1.0): /workspaces/conan_extend_own_cmake_presets/conanfile.py

======== Computing necessary packages ========

======== Installing packages ========

======== Finalizing install (deploy, generators) ========
conanfile.py (foo/1.0): Calling generate()
conanfile.py (foo/1.0): Generators folder: /workspaces/conan_extend_own_cmake_presets/build/Release/generators
conanfile.py (foo/1.0): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (foo/1.0): CMakeToolchain: Preset 'conan-release' added to CMakePresets.json.
    (cmake>=3.23) cmake --preset conan-release
    (cmake<3.23) cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
conanfile.py (foo/1.0): CMakeToolchain generated: /workspaces/conan_extend_own_cmake_presets/build/Release/generators/CMakePresets.json
conanfile.py (foo/1.0): CMakeToolchain generated: /workspaces/conan_extend_own_cmake_presets/ConanPresets.json
conanfile.py (foo/1.0): Generating aggregated env files
conanfile.py (foo/1.0): Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
vscode ➜ /workspaces/conan_extend_own_cmake_presets (master) $ conan install . -s build_type=Debug

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.py (foo/1.0): /workspaces/conan_extend_own_cmake_presets/conanfile.py

======== Computing necessary packages ========

======== Installing packages ========

======== Finalizing install (deploy, generators) ========
conanfile.py (foo/1.0): Calling generate()
conanfile.py (foo/1.0): Generators folder: /workspaces/conan_extend_own_cmake_presets/build/Debug/generators
conanfile.py (foo/1.0): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (foo/1.0): CMakeToolchain: Preset 'conan-debug' added to CMakePresets.json.
    (cmake>=3.23) cmake --preset conan-debug
    (cmake<3.23) cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Debug
conanfile.py (foo/1.0): CMakeToolchain generated: /workspaces/conan_extend_own_cmake_presets/build/Debug/generators/CMakePresets.json
conanfile.py (foo/1.0): CMakeToolchain generated: /workspaces/conan_extend_own_cmake_presets/ConanPresets.json
conanfile.py (foo/1.0): Generating aggregated env files
conanfile.py (foo/1.0): Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
vscode ➜ /workspaces/conan_extend_own_cmake_presets (master) $ cmake --list-presets
CMake Error: Could not read presets from /workspaces/conan_extend_own_cmake_presets:
Invalid preset: "default"
```
Conan and CMake are still the same versions. Changes are only that I copied the whole directory to own project/own directory, adding a devcontainer I'm working in.

Attached the generated JSON files, hopefully this clarify the things.

[ConanPresets.json](https://github.com/user-attachments/files/17705448/ConanPresets.json)
[CMakePresets.json](https://github.com/user-attachments/files/17705455/CMakePresets.json)
[CMakePresets.json](https://github.com/user-attachments/files/17705458/CMakePresets.json)

**Comment by memsharded** [comment]
> Conan and CMake are still the same versions. Changes are only that I copied the whole directory to own project/own directory, adding a devcontainer I'm working in.

I think that ``devcontainer`` might be the difference we were looking for. If you could try repeating the same steps:

- In the original ``examples2`` repo folder, without copying it to another location
- Copying it to another location, but without the ``devcontainer``

Maybe this location would be related:? (in the inner generators folder CMakePresets.json, generated file)

> "toolchainFile": "generators/conan_toolchain.cmake",

The CMake specification says that the ``toolchainFile`` can be relative to the "build" folder. It is possible that using devcontainers change this somehow?

**Comment by memsharded** [comment]
Just tried by copying the folder to another location in my computer, that seems to work fine here too.

**Comment by ibis-hdl** [comment]
A step further. I started with Windows pwsh and it works as expected. Than I started with WSL2/Ubuntu24 and failed :(

```shell
$ pwd
/mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets
$ rm -rf build/
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install conan
$ conan profile detect
$ PYTHONPATH=/mnt/h/work/conan_examples/examples2 python3 ci_test_example.py
- CMakeToolchain: Extending your CMakePresets with Conan generated ones -
Running: conan install .

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.py (foo/1.0): /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/conanfile.py

======== Computing necessary packages ========

======== Installing packages ========

======== Finalizing install (deploy, generators) ========
conanfile.py (foo/1.0): Calling generate()
conanfile.py (foo/1.0): Generators folder: /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/build/Release/generators
conanfile.py (foo/1.0): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (foo/1.0): CMakeToolchain: Preset 'conan-release' added to CMakePresets.json.
    (cmake>=3.23) cmake --preset conan-release
    (cmake<3.23) cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
conanfile.py (foo/1.0): CMakeToolchain generated: /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/build/Release/generators/CMakePresets.json
conanfile.py (foo/1.0): CMakeToolchain generated: /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/ConanPresets.json
conanfile.py (foo/1.0): Generating aggregated env files
conanfile.py (foo/1.0): Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
Elapsed time: 2.43 seconds
Running: conan install . -s build_type=Debug

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.py (foo/1.0): /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/conanfile.py

======== Computing necessary packages ========

======== Installing packages ========

======== Finalizing install (deploy, generators) ========
conanfile.py (foo/1.0): Calling generate()
conanfile.py (foo/1.0): Generators folder: /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/build/Debug/generators
conanfile.py (foo/1.0): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (foo/1.0): CMakeToolchain: Preset 'conan-debug' added to CMakePresets.json.
    (cmake>=3.23) cmake --preset conan-debug
    (cmake<3.23) cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Debug
conanfile.py (foo/1.0): CMakeToolchain generated: /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/build/Debug/generators/CMakePresets.json
conanfile.py (foo/1.0): CMakeToolchain generated: /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/ConanPresets.json
conanfile.py (foo/1.0): Generating aggregated env files
conanfile.py (foo/1.0): Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
Elapsed time: 2.44 seconds
Running: cmake --preset release
CMake Error: Could not read presets from /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets:
Invalid preset: "default"
Elapsed time: 0.02 seconds
Traceback (most recent call last):
  File "/mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets/ci_test_example.py", line 19, in <module>
    run(f"cmake --preset release")
  File "/mnt/h/work/conan_examples/examples2/test/examples_tools.py", line 62, in run
    raise Exception(f"Failed cmd: {cmd}\n{output}")
Exception: Failed cmd: cmake --preset release
CMake Error: Could not read presets from /mnt/h/work/conan_examples/examples2/examples/tools/cmake/cmake_toolchain/extend_own_cmake_presets:
Invalid preset: "default"

```

**Comment by memsharded** [comment]
> A step further. I started with Windows pwsh and it works as expected. Than I started with WSL2/Ubuntu24 and failed :(

Uhm, I think it is not possible to use the same folder, mounted on WSL2, if it has been used before in the Windows host. Are you sure you started in a completely clean state when moved to WSL2? I have experienced similar issues when sharing a project from the Windows folders, mounted via ``/mnt/c/Users...`` in my WSL2, if the project already had files from the Windows execution, that the Linux one was not compatible/ready.

**Comment by ibis-hdl** [comment]
What do you mean with clean state? I removed the build folder before.

**Comment by memsharded** [comment]
> What do you mean with clean state? I removed the build folder before.

yes, remove the ``build`` folder before, but also the generated ``ConanPresets.json`` which I think it is not in the build folder.
The generation of the ``ConanPresets.json``, same as the ``CMakeUserPresets.json`` is cumulative, it adds (``include``) new presets at every ``conan install``. If it is there from the Windows invocation, that would explain the error.

**Comment by memsharded** [comment]
No prob at all for the noise, these things happen, happy to be able to help! :) 

Don't hesitate to create new tickets for any further question or issue. Thanks for the feedback.
